---
name: rudiplatform

services:
  magnolia-database:
    image: postgres:15.8
    restart: unless-stopped
    ports:
      - 35434:5432
    environment:
      - "LC_ALL=C.UTF-8"
      - "POSTGRES_DB=magnolia"
      - "POSTGRES_USER=magnolia"
      - "POSTGRES_PASSWORD=magnolia"
      - "POSTGRES_PORT=5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ./config/magnolia-init/:/docker-entrypoint-initdb.d/
    #  - postgresql_data:/var/lib/postgresql/data
    profiles:
      - magnolia

  magnolia:
    build: ./image/magnolia
    image: rudiplatform/magnolia
    security_opt:
      - seccomp=unconfined
    depends_on:
      - magnolia-database
    ports:
      - "8082:8080"
    volumes:
      - ./config/magnolia:/usr/local/tomcat/webapps/ROOT/WEB-INF/config
      - ./data/magnolia/modules:/opt/magnolia/modules
      - ./data/magnolia/repository:/opt/magnolia/data/repository
    environment:
      - "MAGNOLIA_BDD_HOST=magnolia-database"
      - "MAGNOLIA_BDD_USER=magnolia"
      - "MAGNOLIA_BDD_PASSWORD=magnolia" #NE PAS UTILISER DANS DES CONDITIONS DE PRODUCTIONS POUR DES RAISONS EVIDENTES
      - "MAGNOLIA_REPOSITORY_ROOT=/opt/magnolia/data"
      - "CATALINA_OPTS=-DMAGNOLIA_REPOSITORY_ROOT=\"/opt/magnolia/data\"  -DMAGNOLIA_BDD_HOST=magnolia-database -DMAGNOLIA_BDD_USER=magnolia -DMAGNOLIA_BDD_PASSWORD=magnolia -Xmx2048m -Dmagnolia.update.auto=true"
    profiles:
      - magnolia
