
CREATE USER acl WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

ALTER USER acl SET search_path TO acl_data, public;
ALTER USER acl WITH PASSWORD 'Rud1R00B-db-acl';

CREATE USER kalim WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

ALTER USER kalim SET search_path TO kalim_data, public;
ALTER USER kalim WITH PASSWORD 'Rud1R00B-db-kalim';

CREATE USER konsent WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

ALTER USER konsent SET search_path TO konsent_data, public;
ALTER USER konsent WITH PASSWORD 'Rud1R00B-db-konsent';

CREATE USER kos WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

ALTER USER kos SET search_path TO kos_data, public;
ALTER USER kos WITH PASSWORD 'Rud1R00B-db-kos';

CREATE USER selfdata WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

ALTER USER selfdata SET search_path TO selfdata_data, public;
ALTER USER selfdata WITH PASSWORD 'Rud1R00B-db-selfdata';

CREATE USER strukture WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

ALTER USER strukture SET search_path TO strukture_data, public;
ALTER USER strukture WITH PASSWORD 'Rud1R00B-db-strukture';

CREATE USER template WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

ALTER USER template SET search_path TO template_data, public;
ALTER USER template WITH PASSWORD 'Rud1R00B-db-template';
CREATE USER apigateway WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

ALTER USER apigateway SET search_path TO apigateway_data, public;
ALTER USER apigateway WITH PASSWORD 'Rud1R00B-db-apigateway';

CREATE USER projekt WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

ALTER USER projekt SET search_path TO projekt_data, public;
ALTER USER projekt WITH PASSWORD 'Rud1R00B-db-projekt';
