#FROM coronawhy/solr:8.11.3
FROM solr:9.4.1
USER root

RUN apt-get update && apt-get upgrade -y
#COPY entrypoint.sh /tmp/entrypoint.sh

EXPOSE 8983

# Owner
RUN chown -R solr:solr /tmp
#RUN chmod a+x /tmp/entrypoint.sh
#RUN chmod -R a+r /opt/solr-8.11.3/server/lib/ext/
#RUN chmod -R a+r /opt/solr-8.11.3/contrib/prometheus-exporter/lib/

# Ready !
USER solr
RUN echo "Installing and running Solr for dataverse..."
#CMD ["/tmp/entrypoint.sh"]


